spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/url?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #        url: jdbc:mysql://172.16.20.69:3306/sunshuai?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    #         password: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.number.number.bean  # 注意：对应实体类的路径
